# Generated by Django 6.0.3 on 2026-04-07 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('video', models.FileField(upload_to='videos/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('avg_attention', models.FloatField(blank=True, null=True)),
                ('total_students', models.IntegerField(default=0)),
                ('frames_processed', models.IntegerField(default=0)),
                ('processing_time_sec', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.staff')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subject')),
            ],
            options={
                'ordering': ['-session_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FrameEmotionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_index', models.IntegerField()),
                ('timestamp_sec', models.FloatField()),
                ('face_count', models.IntegerField(default=0)),
                ('avg_attention', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frame_logs', to='engagement.engagementsession')),
            ],
            options={
                'ordering': ['frame_index'],
            },
        ),
        migrations.CreateModel(
            name='StudentAttentionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=200)),
                ('roll_no', models.CharField(blank=True, max_length=50)),
                ('avg_attention', models.FloatField()),
                ('min_attention', models.FloatField(default=0)),
                ('max_attention', models.FloatField(default=0)),
                ('dominant_emotion', models.CharField(blank=True, max_length=50)),
                ('frames_counted', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='engagement.engagementsession')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attention_scores', to='core.student')),
            ],
            options={
                'ordering': ['-avg_attention'],
            },
        ),
    ]
