# Generated by Django 6.0.3 on 2026-04-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementsession',
            name='annotated_video',
            field=models.FileField(blank=True, null=True, upload_to='annotated/'),
        ),
        migrations.AddField(
            model_name='frameemotionlog',
            name='avg_ear',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='frameemotionlog',
            name='avg_pitch',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='frameemotionlog',
            name='avg_yaw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentattentionscore',
            name='avg_ear',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studentattentionscore',
            name='avg_pitch',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studentattentionscore',
            name='avg_roll',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studentattentionscore',
            name='avg_yaw',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studentattentionscore',
            name='ear_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studentattentionscore',
            name='emotion_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studentattentionscore',
            name='eyes_closed_pct',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studentattentionscore',
            name='pose_score',
            field=models.FloatField(default=0),
        ),
    ]
